### ISSUE TITLE
Frontend > Style > Atualizar design dos botões.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#101]
# OVERVIEW 
- No interesse de melhorar o design e disposição dos botões, deixando o uso sobre o sistema mais agradável e intuitivo, a equipe concordou que inverter a ordem dos botões "Editar" e "Visualizar" seria melhor.
- Além disso, algo percebido por Mano Max foi a confusão que, muitas vezes, os botões com os mesmos ícones (olhos) gera ao usuário. Desse modo, é interessante mudar o ícone de "Visualizar atualizações" para outro ícone, como, por exemplo: List, Article, Assignment ou outro similar.

# TASK
- [x] Inverter a ordem dos botões "Editar" e "Visualizar";
- [x] Mudar o ícone de "Visualizar atualizações" para outro ícone, como, por exemplo: List, Article, Assignment ou outro similar.

**Comment by carlos-lucenag** [comment]
#110
