### ISSUE TITLE
Frontend > Fix > Existem campos, no modal de membro, que podem ser enviados vazios e não deviam.

### ISSUE THREAD

**Issue by FLuiz22** [codexjr-dev/projexa-web#131]
# OVERVIEW

- O sistema está permitindo que campos obrigatórios sejam enviados vazios para o backend, o que não deveria acontecer;

# TASKS

- [x] Corrigir o envio dos campos obrigatórios vazios para o back;

**Comment by ManoMax** [comment]
https://github.com/codexjr-dev/projexa-web/issues/6
