### ISSUE TITLE
Frontend > Style > Informar quais campos são obrigatórios e quais não são, ao adicionar um novo membro.

### ISSUE THREAD

**Issue by FLuiz22** [codexjr-dev/projexa-web#132]
# OVERVIEW

- Informar ao usuário quais campos são obrigatórios na criação de um novo membro;

# TASKS

- [ ] Adicionar a informação de quais campos são obrigatórios;

**Comment by ManoMax** [comment]
https://github.com/codexjr-dev/projexa-web/issues/6
