### ISSUE TITLE
Frontend > Feature > Informar que a EJ foi criada.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#17]
# OVERVIEW 
- Um problema crucial e existente no sistema ocorre no momento de cadastro de uma EJ, onde o presidente (usuário responsável por criar a EJ, até o momento), ao clicar no botão de "Criar conta", consegue criar diversas EJs iguais, sem nem ter o conhecimento de que a primeira tentativa já foi válida.
- Para isso, é interessante implementar três soluções que restringirão a possibilidade do mesmo problema acontecer.
  1. Implementar uma notificação de que "A Empresa Júnior está sendo cadastrada", no momento em que o usuário clicar no botão;
  2. Redirecionar o usuário para a Tela de Login, após a resposta da requisição chegar.
  3. No ambiente de Backend, adicionar uma verificação para o caso de uma EJ, com aquele e-mail do presidente, já existir; Retornando, assim, uma resposta de que a EJ já foi criada com aquele e-mail. ([link da Issue para o Backend presente aqui](https://github.com/codexjr-dev/dashboard-codex-api/issues/6))

# TASK
- [x] Implementar uma notificação de que "A Empresa Júnior está sendo cadastrada", no momento em que o usuário clicar no botão.
- [x] Redirecionar o usuário para a Tela de Login, após a resposta da requisição chegar.

# Links:
- Issue of Frontend: https://github.com/codexjr-dev/dashboard-codex-api/issues/6
- Link in Frontend Project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=35169948

**Comment by FLuiz22** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/75

**Comment by ManoMax** [comment]
# COMMENTS

- Para se avaliar:
  - Será se ficaria interessante que a gente adicionasse duas notificações para esse caso?
  - A primeira seria `A Empresa Júnior está sendo cadastrada`, notificado antes de entrar no try catch;
  - E a segunda seria `A Empresa Júnior foi cadastrada com sucesso`, notificado após o await this.createEj(this.cadastroData).

O que você acha, @FLuiz22 ?

**Comment by FLuiz22** [comment]
# COMMENTS
- Alterações feitas e agora tem as duas notificações
