### ISSUE TITLE
Frontend > Fix > Remover console.log ao realizar o login e ao adicionar um novo projeto.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#18]
# OVERVIEW 
- Não trata-se de um problema visível ao usuário comum, no entanto, sabemos que toda segurança de dados é importante no funcionamento de um bom sistema. Desse modo, vale a pena que esses prints não sejam realizados no console do navegador.

# TASK
- [x] Remover o console.log no momento em que o usuário realiza o login.
- [x] Remover o console.log no momento em que o usuário adiciona um novo projeto.

**Comment by maahog** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/25
