### ISSUE TITLE
Frontend > Feature > Informar que é obrigatória a presença de ao menos 1 pessoa/liderança na EJ.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#19]
# OVERVIEW 
- Atualmente, é possível que uma liderança apague todos os demais usuários presentes na EJ, incluindo a si mesmo. Desse modo, ao deslogar-se, ninguém mais terá acesso à aquela EJ. Sendo assim, é importante adicionar restrições ao apagar um usuário, fazendo com que a presença de ao menos um usuário líder da EJ seja obrigatória.

# TASK
- [ ] Informar que é obrigatória a presença de ao menos 1 pessoa/liderança na EJ.

# Links:
- Issue of Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/7
- Link in Backend Project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=34193528

**Comment by maahog** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/68

**Comment by ManoMax** [comment]
# COMMENT

- A Issue ainda não foi pra Review, mas, para adiantar trabalho, andei investigando o andamento da task e percebi um outro caso de verificação importante para essa situação de necessidade de ao menos um liderança:
  - Ao editar um usuário líder para um cargo sem liderança, é importante que haja a mesma notificação;
  - O Backend já está realizando essa verificação e retornando uma mensagem similar a mensagem de quando buscamos excluir o único membro líder.
  - Para o momento de edição, é possível fazer algo similar.

@maahog

**Comment by maahog** [comment]
@ManoMax 

Consegui solucionar a questão das duas caixas "membro removido com sucesso" e "falha ao excluir membro" aparecerem ao mesmo tempo quando uma liderança tentava se excluir, mesmo tendo outra liderança na ej. Porém vale ressaltar que, a caixinha foi removida, mas é necessário que o membro que se excluiu seja redirecionado para a home, portanto, irei criar uma issue referente à isso.
