### ISSUE TITLE
Frontend > Feature > Adicionar notificação caso já exista um membro com o e-mail cadastrado, ao adicionar um novo membro.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#20]
# OVERVIEW 
- Atualmente, é possível que ocorra a tentativa de criação de mais de um membro com o mesmo e-amail.

# TASK
- [x] Caso a resposta da requisição informe essa ocorrência, adicionar notificação da existência de outro membro já cadastrado com aquele e-mail.

# Links:
- Issue of Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/25
- Link in Backend Project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=37028106

**Comment by matheusvictoor** [comment]
[#77](https://github.com/codexjr-dev/dashboard-codex-web/pull/77)
