### ISSUE TITLE
Frontend > Fix > Tornar permissiva a edição de links.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#26]
# OVERVIEW 
- Por algum motivo, as restrições para a edição de links está ocorrendo. Provavelmente seja devido a alguma configuração no model que o botão de edição chama.

# TASK
- [x] Tornar permissiva a edição de links.

**Comment by FLuiz22** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/39
