### ISSUE TITLE
Frontend > Refactor > Adicionar novos Departamentos aos links adicionados.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#27]
# OVERVIEW 
- Atualmente, ao criar um link, o sistema disponibiliza os Departamentos `qualidade` e `projetos`.
- Atualizar essas categorias para `Presidencia`, `Gente & Gestão`, `Projetos`, `Qualidade`, `Marketing` e `Negócios`, será melhor para, futuramente, dividir os links por Departamentos.

# TASK
- [x] Atualizar essas categorias para `Presidencia`, `Gente & Gestão`, `Projetos`, `Qualidade`, `Marketing` e `Negócios`.

**Comment by maahog** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/54
