### ISSUE TITLE
Frontend > Fix > Edição de projetos não funciona.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#29]
# OVERVIEW 
- Ao editar alguma informação do projeto e clicar no botão "Salvar", nenhuma requisição está sendo enviada, fazendo com que essa ação não funcione no sistema.

# TASK
- [x] Verificar o não envio de requisição e corrigir.

**Comment by FLuiz22** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/41
