### ISSUE TITLE
Frontend > Refactor > Adicionar novos roles como disponíveis na página de "Adicionar Usuário".

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#31]
# OVERVIEW 
- As atuais Funções disponíveis nos campos de "Adicionar usuário" são: `Assessor(a)`, `Diretor(a)`, `Presidente` e `Conselheiro(a)`.
- Para melhor gestão de antigos membros da EJ ou para dar acesso aos Guardiões e Trainees, essas opções podem ser ampliadas com `Pós-Júnior`, `Guardiã(o)`, `Trainee` e `Ex-Trainee`.

# TASK
- [x] Atualizar as funções citadas.

**Comment by Anaritamed** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/35
