### ISSUE TITLE
Frontend > Refactor > Atualizar todas as verificações de role == "presidente" nas páginas.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#32]
# OVERVIEW 
- Com a atualização de roles disponíveis para os membros, a antiga função `presidente` agora tornou-se `Presidente`;
- Isso fez com que uma série de verificações no ambiente Frontend, não reconhecesse o usuário com essa função como um usuário de acesso maior;

# TASK
- [ ] Atualize as páginas a botões que verificam a função `presidente` para a função `Presidente`.

**Comment by FLuiz22** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/34
