### ISSUE TITLE
Frontend > Refactor > Adicionar novos roles como disponíveis na página de "Adicionar Membro".

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#36]
# OVERVIEW 
- As atuais Funções disponíveis nos campos de "Adicionar membro" são: `Assessor(a)`, `Diretor(a)`, `Presidente` e `Conselheiro(a)`.
- Para melhor gestão de antigos membros da EJ ou para dar acesso aos Guardiões e Trainees, essas opções podem ser ampliadas com `Pós-Júnior`, `Guardiã(o)`, `Trainee` e `Ex-Trainee`.
- Essa Task já havia sido resolvida no contexto de usuário, mas, após atualizações sobre o sistema, membro é o modelo utilizado como acesso dos usuários do sistema.

# TASK
- [x] Atualizar as funções citadas.

**Comment by maahog** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/40
