### ISSUE TITLE
Frontend > Feature > [Atualizações de Projetos] Novos 2 ícones nas ações de cada Projeto.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#43]
# OVERVIEW 
- Com as novas rotas de adicionar atualizações (news), edita-las, visualizar todas e remove-las, agora devemos criar dois botões presentes em cada ocorrência da listagem de projetos.
- Esses botões devem ser de `criar uma nova atualização` e de `visualizar todas as atualizações`;
- No caso de `Criar atualização`, deve-se verificar se o membro participa do projeto ou é líder;
- No caso de `Ler atualizações`, todos podem ter acesso;

# TASK
- [x] Criar ícone de `Criar atualização`, com a verificação de se o membro participa do projeto ou é líder;
- [x] Criar ícone de `Ler atualização`;

# Links:
- Issue of Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/40
- Link in Backend Project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=37557104

**Comment by FLuiz22** [comment]
#83

**Comment by ManoMax** [comment]
# COMMENTS

- Ao adicionar os novos 2 ícones, a visualização de seus respectivos ícones ficou bem ruim, isso foi devido ao fato de que ficaram bem pequenos;

- Um outro problema surgiu quanto ao uso da função `onTeam` no Contexto de Assessor;
- Por se tratar de uma função assíncrona, a verificação do `v-if` (no componente `div.actions-button`) não funciona;

- Outro problema foi quanto ao `row.team.includes(info.sub._id)`, que estava procurando o `info.sub._id` em um array de objetos, ao invés de um array de Strings (de _id's);

- Todas essas questões foram solucionadas no seguinte commit: https://github.com/codexjr-dev/dashboard-codex-web/pull/83/commits/875bc3ed71fac7d5bb022f1286fc4e6b93337a47
