### ISSUE TITLE
Frontend > Refactor > Atualizar e adicionar novas opções as tags presentes nos Links.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#60]
# OVERVIEW 
- As atuais Tags disponíveis nos campos de "Adicionar link" são: `treinamento` e `importante`.
- Para deixar mais organizado e ampliar as opções, poderíamos utilizar `Treinamento`, `Importante`, `Documentação`.
  - Futuramente, essas Tags poderão ser dinamicamente criadas pelos próprios usuários, mas por enquanto, deixaremos somente com essas três opções.

# TASK
- [x] Atualizar as tags citadas.

# LINKS:
- Issue of Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/47
- Issue of Backend in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=37834402

**Comment by Anaritamed** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/67
