### ISSUE TITLE
Frontend > Refactor > Atualizar e adicionar novas opções as tags presentes nos Projetos.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#61]
# OVERVIEW 
- As atuais Tags disponíveis nos campos de "Adicionar projeto" são: `backend`, `frontend`, `wordpress`, `assessoria` e `treinamento`.
- Para deixar mais organizado e ampliar as opções, poderíamos utilizar `Backend`, `Frontend`, `Mobile`, `Wordpress`, `Assessoria` e `Treinamento`.

# TASK
- [x] Atualizar as tags citadas.

# LINKS:
- Issue of Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/48
- Issue of Backend in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=37865111

**Comment by Anaritamed** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/66

**Comment by ManoMax** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/70
