### ISSUE TITLE
Frontend > Refactor > Atualizar e adicionar novas opções as Habilidades presentes nos Membros.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#62]
# OVERVIEW 
- As atuais Habilidades disponíveis nos campos de "Adicionar membro" são: `Backend`, `Frontend` e `Comunicação`.
- Para ampliar as opções, poderíamos utilizar `Backend`, `Frontend`, `Mobile`, `Wordpress`, `Assessoria`, `Treinamento`, `Comunicação`, `Gestão de Projetos`, `Gestão de Pessoas`, `Negociação` e `Documentação`.
  - Futuramente, essas Habilidades poderão ser dinamicamente criadas pelos próprios usuários, mas por enquanto, deixaremos somente com essas três opções.
  - Exemplos de novas Tags: Java, Python, JavaScript, HTML, CSS, React, React Native, MongoDB, Mongoose, Express, Vue, Angular, TypeScript, JWT, Github, Gitlab, Git, Kanbam, Jimp, Figma, Miro, PHP, SQLite, SQL, PL/SQL, Django, Docker, Pandas, AWS, Socker.io, .Net, SCRUM, Scrum Master, Tech Leader, Product Owner, Quality Assurance, etc.

# TASK
- [x] Atualizar as Habilidades citadas.

**Comment by FLuiz22** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/71
