### ISSUE TITLE
Frontend > Feature > Adicionar notificação de "Preencha os campos obrigatórios" no model de "Adicionar Link".

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#64]
# OVERVIEW 
- No model de "Adicionar membro", apesar de não registrar os dados, caso os campos obrigatórios estejam incompletos, tais models não informam essa obrigatoriedade.
- Desse modo, adicione a notificação para o caso de algum dos seguintes campos estarem sem preenchimento: `Nome`, `URL`, `Tags` e `Departamentos`.

# TASK
- [x] Garantir o não envio de requisição ao Backend, caso algum desses campos obrigatórios não tenha sido preenchido;
- [x] Notificar ao usuário que os campos precisam ser preenchidos (acima ou abaixo do botão "Salvar" é um bom local);

**Comment by maahog** [comment]
https://github.com/codexjr-dev/projexa-web/pull/147

**Comment by FLuiz22** [comment]
# COMMENTS

- Preenchendo os campos ou não, o botão de salvar não funciona;
- O motivo para isso é o fato de não ter uma referência da função que está sendo emitida do arquivo AdicionarLink para o arquivo Link;

Obs: Com isso corrigido, existe outro fator a ser considerado que é quando um link é salvo, mas o seguinte não tem os campos preenchidos, quando isso acontece, a requisição está sendo feita pois as variáveis no Link.vue não foram atualizadas para false novamente, assim, permitindo que a requisição seja feita e a mensagem de campo obrigatório não seja disparada;
