### ISSUE TITLE
Frontend > Feature > Validar o formato do e-mail ao adicionar um novo membro.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#78]
# OVERVIEW 
- Atualmente tem sido possível criar um novo membro com qualquer valor no campo de e-mail, sendo esse valor diferente de qualquer outro e-mail já registrado;
- Desse modo, valores que não correspondem ao regex ideal para o campo de e-mail estão sendo registrados e isso não deveria ser possível.

# TASK
- [x] Adicionar validação ao formato do e-mail, no Model de Adicionar Membro.

**Comment by matheusvictoor** [comment]
#82

**Comment by ManoMax** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/85
