### ISSUE TITLE
Frontend > Fix > Algumas datas estão sendo exibidas com um dia de diferença.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#98]
# OVERVIEW 
- O primeiro caso ocorreu na data de nascimento de `Renan Chaves`, onde o correto seria que a data exposta fosse `06/09/2002`, mas, ao invés disso, a data é exibida como `05/09/2022`.
- No entanto, tanto as `Datas de aniversário` quanto as `Datas de inicio dos projetos` estão com esse decréscimo de dia.

# TASK
- [x] Identificar e corrigir o bug.

**Comment by ManoMax** [comment]
# COMMENTS

- Dica: Sinavez utilizou uma solução para isso. Entrar em contato com `Mateus Faria` (Qualidade).

**Comment by matheusvictoor** [comment]
#109
